version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run: apt-get update && apt-get install -y sudo
      - run: sudo bash <(curl https://bit.ly/flamerecca-vim -L)
