version: 2
jobs:
  build:
    docker:
      - image: debian:8-slim
    steps:
      - checkout
      - run: apt-get update && apt-get install -y sudo curl git vim ncurses-term xterm
      - run: export TERM=xterm
      - run: sudo su -Ec 'echo $TERM'
      - run: sudo su -Ec 'bash <(curl https://bit.ly/flamerecca-vim -L)'
