version: 2 # use CircleCI 2.0

jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    macos:
      xcode: "9.0"
  steps: # a set of executable commands
      - run: sudo bash <(curl https://bit.ly/flamerecca-vim -L)
